import React from 'react';

import Paths from './Paths';

export const statesAbb = [
    'AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA',
    'HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA',
    'MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND',
    'OH','OK','OR','PW','PA','PR','RI','SC','SD','TN','TX','UT',
    'VT','VI','VA','WA','WV','WI','WY'
];

export const states = [
    {
        name: 'Connecticut',
        key: 'connecticut',
        counties: [
            'Fairfield', 'Hartford', 'Litchfield', 'Middlesex', 'New Haven', 'New London',
            'Tolland', 'Windham'
        ]
    },
    {
        name: 'New Jersey',
        key: 'new-jersey',
        path: 'newJersey',
        counties: [
            'Atlantic', 'Bergen', 'Burlington', 'Camden', 'Cape May', 'Cumberland',
            'Essex', 'Gloucester', 'Hudson', 'Hunterdon', 'Mercer', 'Middlesex',
            'Monmouth', 'Morris', 'Ocean', 'Passaic', 'Salem', 'Somerset',
            'Sussex', 'Union', 'Warren'
        ]
    },
    {
        name: 'Pennsylvania',
        key: 'pennsylvania',
        counties: [
            'Adams', 'Allegheny', 'Armstrong', 'Beaver', 'Bedford', 'Berks',
            'Blair', 'Bradford', 'Bucks', 'Butler', 'Cambria', 'Cameron',
            'Carbon', 'Centre', 'Chester', 'Clarion', 'Clearfield', 'Clinton',
            'Columbia', 'Crawford', 'Cumberland', 'Dauphin', 'Delaware', 'Elk',
            'Erie', 'Fayette', 'Forest', 'Franklin', 'Fulton', 'Greene',
            'Huntingdon', 'Indiana', 'Jefferson', 'Juniata', 'Lackawanna', 'Lancaster',
            'Lawrence', 'Lebanon', 'Lehigh', 'Luzerne', 'Lycoming', 'McKean',
            'Mercer', 'Mifflin', 'Monroe', 'Montgomery', 'Montour', 'Northampton',
            'Northumberland', 'Perry', 'Philadelphia', 'Pike', 'Potter', 'Schuylkill',
            'Snyder', 'Somerset', 'Sullivan', 'Susquehanna', 'Tioga', 'Union',
            'Venango', 'Warren', 'Washington', 'Wayne', 'Westmoreland', 'Wyoming',
            'York'
        ]
    }
];

export const dumpsterSizes = [
    {
        size: '10', page: Paths.tenYardDumpster,
        length: '10', width: '8', height: '3.5', tons: '2',
        pickup: '4', garbageBags: '50',
        page: Paths.tenYardDumpster
    },
    {
        size: '15', page: Paths.tenYardDumpster,
        length: '16', width: '8', height: '4', tons: '2.5', 
        pickup: '6', garbageBags: '75',
    },
    {
        size: '20', page: Paths.twentyYardDumpster,
        length: '20', width: '8', height: '3.5', tons: '3', 
        pickup: '8', garbageBags: '100',
        page: Paths.twentyYardDumpster
    },
    {
        size: '30', page: Paths.thirtyYardDumpster,
        length: '20', width: '8', height: '5', tons: '4', 
        pickup: '12', garbageBags: '150',
        page: Paths.thirtyYardDumpster
    },
    {
        size: '40', page: Paths.fortyYardDumpster,
        length: '20', width: '8', height: '7', tons: '5', 
        pickup: '16', garbageBags: '200',
        page: Paths.fortyYardDumpster
    },
];

export const charges = {
    tripCharge: 150.00,
    extensionFee: 10.00,
    baseRentalPeriod: 14
}

export const materials = {
    cND: 'Construction & Demolition',
    bulky13: 'Household Items',
    bNB: 'Brush & Branch',
    roofing: 'Roofing',
    concrete: 'Clean Concrete',
    comix: 'Concrete & Brick Mix',
    concreteRebar: 'Concrete With Rebar',
    asphalt: 'Asphalt',
    other: 'Other'
}

export const salesTax = [
    {state: 'CT', amount: 0.0635},
    {state: 'NJ', amount: 0.06625},
    {state: 'PA', amount: 0.06}
];

export const AdditionalTerms = () => (
    <div>
        <div style={{marginBottom: 12}}>
            <span style={{fontWeight: 600}}>Waste Material</span> - The waste material to be collected and disposed of or processed by Alliance Disposal or its partners is Bulky Waste, Construction and Demolition Waste, Class A recyclables, and Class B recyclables generated by the Customer as defined by N.J.A.C. 7:26 and N.J.A.C. 7:26A.  Waste shall only include such wastes that are acceptable at disposal facilities approved by the State or local agencies. Customer will not deliver for collection any dangerous materials including but not limited to the Prohibited Waste listed herein.  Prohibited Waste includes food waste, industrial waste, waste containing asbestos, septic tanks &amp; waste, biomedical waste, pesticides, solvents, oil, oil filters, oil containers, gas cans, propane tanks, batteries of any kind, appliances with Freon (air conditioners, refrigerators, etc.), Freon aerosol cans, foam aerosol cans, electronics (e.g., TV's, computers, monitors, computer parts, radios, etc.), and Hazardous Waste (e.g., ballasts with PCB's, devices containing mercury, fluorescent bulbs, etc.).  At Alliance Disposal’s or its partners’ discretion, Alliance Disposal may charge Customer an additional disposal fee to transport and dispose of Prohibited Waste and commingled waste.
        </div>

        <div style={{marginBottom: 12}}>
            <span style={{fontWeight: 600}}>Overweight Containers</span> – Any overweight (overage) charges are due and payable upon removal of the container and Alliance Disposal has the right to automatically charge your payment method on file.
        </div>

        <div style={{marginBottom: 12}}>
            <span style={{fontWeight: 600}}>Overfilled Containers</span> - Alliance Disposal or its partners reserves the right to refuse to remove an overfilled container.  If overfilled, the Customer will be responsible for removing overfilled debris below the top of the container.  If overfilled, Alliance Disposal may charge Customer an additional fee for a “dry run” to remove the container.
        </div>

        <div style={{marginBottom: 12}}>
            <span style={{fontWeight: 600}}>Wait Time</span> – Driver must have access to service the container within thirty (30) minutes of arrival to the site.  If the driver is delayed longer than thirty (30) minutes, waiting time shall be charged at a rate of ${charges.tripCharge} per half hour.
        </div>

        <div style={{marginBottom: 12}}>
            <span style={{fontWeight: 600}}>Daily Rental Fee</span> – A daily rental fee of ${charges.extensionFee} per day will apply after the containers is not exchanged or returned in fourteen ({charges.baseRentalPeriod}) days, or if applicable by the custom expiration date purchased.  If the container is exchanged then the daily rental period starts over again.
        </div>
    </div>
);